version: "3.8"
services:
  postgres:
    image: postgres:latest
    env_file:
      - djangoResume/docker.env
    ports:
      - "5432:5432"
    volumes:
      - "postgresql-data:/var/lib/postgresql/data"
    command: -p 5432
  app:
    container_name: djangoResume
    hostname: djangoResume
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    env_file:
      - djangoResume/docker.env
    volumes:
      - .:/srv/app
    ports:
      - "0.0.0.0:8000:8000"
    command: gunicorn djangoResume.wsgi:application --bind 0.0.0.0:8000

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
    - app
    ports:
      - 80:80



volumes:
  postgresql-data:
  static-data: